version: "3.2"
services:
  db:
    mem_limit: 1G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    image: postgres:15.3
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    - ./backup:/backup
