version: "3.2"
services:
  db:
    mem_limit: 1G
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    volumes:
    - ./data:/var/opt/mssql
    - ./backup:/backup
